const Emojis = () => {
	return (
        <ul className='emoji-list'>
			<li>😀</li>
			<li>😄</li>
			<li>😁</li>
			<li>😆</li>
			<li>😅</li>
			<li>😂</li>
			<li>🤣</li>
			<li>😊</li>
			<li>😇</li>
			<li>🙂</li>
			<li>🙃</li>
			<li>😉</li>
			<li>😌</li>
			<li>😍</li>
			<li>🥰</li>
			<li>😘</li>
			<li>😗</li>
			<li>😙</li>
			<li>😚</li>
			<li>😋</li>
			<li>😛</li>
			<li>😝</li>
			<li>😜</li>
			<li>🤪</li>
			<li>🤨</li>
			<li>🧐</li>
			<li>🤓</li>
			<li>😎</li>
			<li>🤩</li>
			<li>🥳</li>
			<li>😏</li>
			<li>😒</li>
			<li>😞</li>
			<li>😔</li>
			<li>😟</li>
			<li>😕</li>
			<li>🙁</li>
			<li>☹️</li>
			<li>😣</li>
			<li>😖</li>
			<li>😫</li>
			<li>😩</li>
			<li>🥺</li>
			<li>😢</li>
			<li>😭</li>
			<li>😤</li>
			<li>😠</li>
			<li>😡</li>
			<li>🤬</li>
			<li>🤯</li>
			<li>😳</li>
			<li>🥵</li>
			<li>🥶</li>
			<li>😱</li>
			<li>😨</li>
			<li>😰</li>
			<li>😥</li>
			<li>😓</li>
			<li>🤗</li>
			<li>🤔</li>
			<li>🤭</li>
			<li>🤫</li>
			<li>🤥</li>
			<li>😶</li>
			<li>😐</li>
			<li>😑</li>
			<li>😬</li>
			<li>🙄</li>
			<li>😯</li>
			<li>😦</li>
			<li>😧</li>
			<li>😮</li>
			<li>😲</li>
			<li>🥱</li>
			<li>😴</li>
			<li>🤤</li>
			<li>😪</li>
			<li>😵</li>
			<li>🤐</li>
			<li>🥴</li>
			<li>🤢</li>
			<li>🤮</li>
			<li>🤧</li>
			<li>😷</li>
			<li>🤒</li>
			<li>🤕</li>
			<li>🤑</li>
			<li>🤠</li>
			<li>😈</li>
			<li>👿</li>
			<li>👹</li>
			<li>👺</li>
			<li>🤡</li>
			<li>💩</li>
			<li>👻</li>
			<li>💀</li>
			<li>☠️</li>
			<li>👽</li>
			<li>👾</li>
			<li>🤖</li>
			<li>🎃</li>
			<li>😺</li>
			<li>😸</li>
			<li>😹</li>
			<li>😻</li>
			<li>😼</li>
			<li>😽</li>
			<li>🙀</li>
			<li>😿</li>
			<li>😾</li>
	    </ul>
    );
}

export default Emojis;